### ISSUE TITLE
Question about inconsistency of trainable parameters on each dataset.

### ISSUE THREAD

**Issue by xiaoli1996** [MichaelLynn1996/AAT#2]
Thanks for the code for interesting work! I keep the same adapter configuration in your paper called AST^{MS}: ‘spatial mlp’, but I find that the number of trainable parameters is not consistent on each dataset: ESC50 7.141/94.396M; speechcommandv1: 7.126/94.031M; speechcommandv2: 7.129/94.034M; urbansound8k: 7.110/94.264M; openmic:7.118/94.843M; gtzan:7.110/96.660M.  
Can you tell me what causes this?

**Comment by MichaelLynn1996** [comment]
Hello there,
In response to this issue, it is because when using an Adapter, the classification head is also trainable. However, each dataset has different classes, so the parameters will also have minor differences.

**Comment by MichaelLynn1996** [comment]
> Thanks for the code for interesting work! I keep the same adapter configuration in your paper called AST^{MS}: ‘spatial mlp’, but I find that the number of trainable parameters is not consistent on each dataset: ESC50 7.141/94.396M; speechcommandv1: 7.126/94.031M; speechcommandv2: 7.129/94.034M; urbansound8k: 7.110/94.264M; openmic:7.118/94.843M; gtzan:7.110/96.660M. Can you tell me what causes this?

Hello there,
In response to this issue, it is because when using an Adapter, the classification head is also trainable. However, each dataset has different classes, so the parameters will also have minor differences.

**Comment by xiaoli1996** [comment]
Thanks very much for your answer! I will close this issue.
